[package]
name = "domain"
version = "0.1.0"
authors = ["Antoine Carton"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
serde = "1.0.123"
serde_derive = "1.0.123"
mockall = "0.9.1"
